CREATE TABLE "public"."stories" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "created_at" timestamptz DEFAULT now() NOT NULL,
  "baby_id" uuid NOT NULL,
  "created_by" uuid DEFAULT auth.uid(),
  "media_path" character varying NOT NULL,
  "thumbnail_path" character varying,
  "mime_type" character varying NOT NULL,
  "caption" character varying,
  "expires_at" timestamptz
);

ALTER TABLE "public"."stories" OWNER TO "postgres";

ALTER TABLE ONLY "public"."stories"
    ADD CONSTRAINT "stories_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."stories"
    ADD CONSTRAINT "stories_baby_id_fkey" FOREIGN KEY ("baby_id") REFERENCES "public"."babies"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."stories"
    ADD CONSTRAINT "stories_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE SET NULL;

GRANT ALL ON TABLE "public"."stories" TO "anon";
GRANT ALL ON TABLE "public"."stories" TO "authenticated";
GRANT ALL ON TABLE "public"."stories" TO "service_role";

-- Same "no circle = hidden, admin-only" rule as posts_circles/events_circles.
CREATE TABLE "public"."stories_circles" (
  "story_id" uuid NOT NULL,
  "circle_id" uuid NOT NULL
);

ALTER TABLE "public"."stories_circles" OWNER TO "postgres";

ALTER TABLE ONLY "public"."stories_circles"
    ADD CONSTRAINT "stories_circles_pkey" PRIMARY KEY ("story_id", "circle_id");

ALTER TABLE ONLY "public"."stories_circles"
    ADD CONSTRAINT "stories_circles_story_id_fkey" FOREIGN KEY ("story_id") REFERENCES "public"."stories"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."stories_circles"
    ADD CONSTRAINT "stories_circles_circle_id_fkey" FOREIGN KEY ("circle_id") REFERENCES "public"."circles"("id") ON DELETE CASCADE;

GRANT ALL ON TABLE "public"."stories_circles" TO "anon";
GRANT ALL ON TABLE "public"."stories_circles" TO "authenticated";
GRANT ALL ON TABLE "public"."stories_circles" TO "service_role";

-- Mirrors post_views exactly.
CREATE TABLE "public"."story_views" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "story_id" uuid NOT NULL,
  "user_id" uuid DEFAULT auth.uid() NOT NULL,
  "viewed_at" timestamptz DEFAULT now() NOT NULL
);

ALTER TABLE "public"."story_views" OWNER TO "postgres";

ALTER TABLE ONLY "public"."story_views"
    ADD CONSTRAINT "story_views_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."story_views"
    ADD CONSTRAINT "story_views_story_id_user_id_key" UNIQUE ("story_id", "user_id");

ALTER TABLE ONLY "public"."story_views"
    ADD CONSTRAINT "story_views_story_id_fkey" FOREIGN KEY ("story_id") REFERENCES "public"."stories"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."story_views"
    ADD CONSTRAINT "story_views_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE CASCADE;

GRANT ALL ON TABLE "public"."story_views" TO "anon";
GRANT ALL ON TABLE "public"."story_views" TO "authenticated";
GRANT ALL ON TABLE "public"."story_views" TO "service_role";

-- Named, non-expiring collections of stories (Instagram Highlights). Membership
-- in story_highlight_items is what protects a story from pruneExpiredStories
-- once its own expires_at has passed.
CREATE TABLE "public"."story_highlights" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "baby_id" uuid NOT NULL,
  "created_by" uuid DEFAULT auth.uid(),
  "name" character varying NOT NULL,
  "cover_story_id" uuid,
  "created_at" timestamptz DEFAULT now() NOT NULL
);

ALTER TABLE "public"."story_highlights" OWNER TO "postgres";

ALTER TABLE ONLY "public"."story_highlights"
    ADD CONSTRAINT "story_highlights_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."story_highlights"
    ADD CONSTRAINT "story_highlights_baby_id_fkey" FOREIGN KEY ("baby_id") REFERENCES "public"."babies"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."story_highlights"
    ADD CONSTRAINT "story_highlights_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE SET NULL;

ALTER TABLE ONLY "public"."story_highlights"
    ADD CONSTRAINT "story_highlights_cover_story_id_fkey" FOREIGN KEY ("cover_story_id") REFERENCES "public"."stories"("id") ON DELETE SET NULL;

GRANT ALL ON TABLE "public"."story_highlights" TO "anon";
GRANT ALL ON TABLE "public"."story_highlights" TO "authenticated";
GRANT ALL ON TABLE "public"."story_highlights" TO "service_role";

CREATE TABLE "public"."story_highlight_items" (
  "highlight_id" uuid NOT NULL,
  "story_id" uuid NOT NULL,
  "position" integer DEFAULT 0 NOT NULL
);

ALTER TABLE "public"."story_highlight_items" OWNER TO "postgres";

ALTER TABLE ONLY "public"."story_highlight_items"
    ADD CONSTRAINT "story_highlight_items_pkey" PRIMARY KEY ("highlight_id", "story_id");

ALTER TABLE ONLY "public"."story_highlight_items"
    ADD CONSTRAINT "story_highlight_items_highlight_id_fkey" FOREIGN KEY ("highlight_id") REFERENCES "public"."story_highlights"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."story_highlight_items"
    ADD CONSTRAINT "story_highlight_items_story_id_fkey" FOREIGN KEY ("story_id") REFERENCES "public"."stories"("id") ON DELETE CASCADE;

GRANT ALL ON TABLE "public"."story_highlight_items" TO "anon";
GRANT ALL ON TABLE "public"."story_highlight_items" TO "authenticated";
GRANT ALL ON TABLE "public"."story_highlight_items" TO "service_role";

ALTER TYPE "public"."notification_type" ADD VALUE 'new_story';
