CREATE TABLE "public"."story_reactions" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "story_id" uuid NOT NULL,
  "user_id" uuid DEFAULT auth.uid() NOT NULL,
  "emoji" character varying DEFAULT '❤️' NOT NULL,
  "created_at" timestamptz DEFAULT now() NOT NULL
);

ALTER TABLE "public"."story_reactions" OWNER TO "postgres";

ALTER TABLE ONLY "public"."story_reactions"
    ADD CONSTRAINT "story_reactions_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."story_reactions"
    ADD CONSTRAINT "story_reactions_story_id_user_id_key" UNIQUE ("story_id", "user_id");

ALTER TABLE ONLY "public"."story_reactions"
    ADD CONSTRAINT "story_reactions_story_id_fkey" FOREIGN KEY ("story_id") REFERENCES "public"."stories"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."story_reactions"
    ADD CONSTRAINT "story_reactions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE CASCADE;

GRANT ALL ON TABLE "public"."story_reactions" TO "anon";
GRANT ALL ON TABLE "public"."story_reactions" TO "authenticated";
GRANT ALL ON TABLE "public"."story_reactions" TO "service_role";

ALTER TYPE "public"."notification_type" ADD VALUE 'new_story_reaction';
