CREATE TABLE "public"."post_views" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "post_id" uuid NOT NULL,
  "user_id" uuid DEFAULT auth.uid() NOT NULL,
  "viewed_at" timestamptz DEFAULT now() NOT NULL
);

ALTER TABLE "public"."post_views" OWNER TO "postgres";

ALTER TABLE ONLY "public"."post_views"
    ADD CONSTRAINT "post_views_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."post_views"
    ADD CONSTRAINT "post_views_post_id_user_id_key" UNIQUE ("post_id", "user_id");

ALTER TABLE ONLY "public"."post_views"
    ADD CONSTRAINT "post_views_post_id_fkey" FOREIGN KEY ("post_id") REFERENCES "public"."posts"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."post_views"
    ADD CONSTRAINT "post_views_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE CASCADE;

GRANT ALL ON TABLE "public"."post_views" TO "anon";
GRANT ALL ON TABLE "public"."post_views" TO "authenticated";
GRANT ALL ON TABLE "public"."post_views" TO "service_role";
