CREATE TABLE "public"."posts" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "created_at" timestamptz DEFAULT now() NOT NULL,
  "baby_id" uuid NOT NULL,
  "created_by" uuid DEFAULT auth.uid() NOT NULL,
  "taken_at" date NOT NULL DEFAULT current_date,
  "caption" character varying
);

ALTER TABLE "public"."posts" OWNER TO "postgres";

ALTER TABLE ONLY "public"."posts"
    ADD CONSTRAINT "posts_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."posts"
    ADD CONSTRAINT "posts_baby_id_fkey" FOREIGN KEY ("baby_id") REFERENCES "public"."babies"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."posts"
    ADD CONSTRAINT "posts_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE SET NULL;

GRANT ALL ON TABLE "public"."posts" TO "anon";
GRANT ALL ON TABLE "public"."posts" TO "authenticated";
GRANT ALL ON TABLE "public"."posts" TO "service_role";

-- Multi-circle visibility, mirroring events_circles: no circle = hidden, admin-only.
CREATE TABLE "public"."posts_circles" (
  "post_id" uuid NOT NULL,
  "circle_id" uuid NOT NULL
);

ALTER TABLE "public"."posts_circles" OWNER TO "postgres";

ALTER TABLE ONLY "public"."posts_circles"
    ADD CONSTRAINT "posts_circles_pkey" PRIMARY KEY ("post_id", "circle_id");

ALTER TABLE ONLY "public"."posts_circles"
    ADD CONSTRAINT "posts_circles_post_id_fkey" FOREIGN KEY ("post_id") REFERENCES "public"."posts"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."posts_circles"
    ADD CONSTRAINT "posts_circles_circle_id_fkey" FOREIGN KEY ("circle_id") REFERENCES "public"."circles"("id") ON DELETE CASCADE;

GRANT ALL ON TABLE "public"."posts_circles" TO "anon";
GRANT ALL ON TABLE "public"."posts_circles" TO "authenticated";
GRANT ALL ON TABLE "public"."posts_circles" TO "service_role";

CREATE TABLE "public"."post_photos" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "post_id" uuid NOT NULL,
  "storage_path" character varying NOT NULL,
  "position" integer DEFAULT 0 NOT NULL,
  "created_at" timestamptz DEFAULT now() NOT NULL
);

ALTER TABLE "public"."post_photos" OWNER TO "postgres";

ALTER TABLE ONLY "public"."post_photos"
    ADD CONSTRAINT "post_photos_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."post_photos"
    ADD CONSTRAINT "post_photos_post_id_fkey" FOREIGN KEY ("post_id") REFERENCES "public"."posts"("id") ON DELETE CASCADE;

GRANT ALL ON TABLE "public"."post_photos" TO "anon";
GRANT ALL ON TABLE "public"."post_photos" TO "authenticated";
GRANT ALL ON TABLE "public"."post_photos" TO "service_role";

CREATE TABLE "public"."post_reactions" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "post_id" uuid NOT NULL,
  "user_id" uuid DEFAULT auth.uid() NOT NULL,
  "emoji" character varying DEFAULT '❤️' NOT NULL,
  "created_at" timestamptz DEFAULT now() NOT NULL
);

ALTER TABLE "public"."post_reactions" OWNER TO "postgres";

ALTER TABLE ONLY "public"."post_reactions"
    ADD CONSTRAINT "post_reactions_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."post_reactions"
    ADD CONSTRAINT "post_reactions_post_id_user_id_key" UNIQUE ("post_id", "user_id");

ALTER TABLE ONLY "public"."post_reactions"
    ADD CONSTRAINT "post_reactions_post_id_fkey" FOREIGN KEY ("post_id") REFERENCES "public"."posts"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."post_reactions"
    ADD CONSTRAINT "post_reactions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE CASCADE;

GRANT ALL ON TABLE "public"."post_reactions" TO "anon";
GRANT ALL ON TABLE "public"."post_reactions" TO "authenticated";
GRANT ALL ON TABLE "public"."post_reactions" TO "service_role";

CREATE TABLE "public"."post_comments" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "post_id" uuid NOT NULL,
  "user_id" uuid DEFAULT auth.uid() NOT NULL,
  "circle_ids" uuid[] DEFAULT '{}' NOT NULL,
  "created_at" timestamptz DEFAULT now() NOT NULL,
  "body" character varying NOT NULL
);

ALTER TABLE "public"."post_comments" OWNER TO "postgres";

ALTER TABLE ONLY "public"."post_comments"
    ADD CONSTRAINT "post_comments_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."post_comments"
    ADD CONSTRAINT "post_comments_post_id_fkey" FOREIGN KEY ("post_id") REFERENCES "public"."posts"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."post_comments"
    ADD CONSTRAINT "post_comments_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE CASCADE;

GRANT ALL ON TABLE "public"."post_comments" TO "anon";
GRANT ALL ON TABLE "public"."post_comments" TO "authenticated";
GRANT ALL ON TABLE "public"."post_comments" TO "service_role";
