-- Polls: optional, zero-or-one per post. question is distinct from posts.caption.
-- UNIQUE(post_id) enforces at most one poll per post without a nullable column on posts.
CREATE TABLE "public"."polls" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "post_id" uuid NOT NULL,
  "created_by" uuid DEFAULT auth.uid() NOT NULL,
  "question" character varying NOT NULL,
  "created_at" timestamptz DEFAULT now() NOT NULL
);
ALTER TABLE "public"."polls" OWNER TO "postgres";
ALTER TABLE ONLY "public"."polls" ADD CONSTRAINT "polls_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."polls" ADD CONSTRAINT "polls_post_id_key" UNIQUE ("post_id");
ALTER TABLE ONLY "public"."polls" ADD CONSTRAINT "polls_post_id_fkey" FOREIGN KEY ("post_id") REFERENCES "public"."posts"("id") ON DELETE CASCADE;
ALTER TABLE ONLY "public"."polls" ADD CONSTRAINT "polls_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE SET NULL;
GRANT ALL ON TABLE "public"."polls" TO "anon";
GRANT ALL ON TABLE "public"."polls" TO "authenticated";
GRANT ALL ON TABLE "public"."polls" TO "service_role";

-- Free-text options, 2-6 per poll (enforced in the server action, not the DB).
CREATE TABLE "public"."poll_options" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "poll_id" uuid NOT NULL,
  "label" character varying NOT NULL,
  "position" integer DEFAULT 0 NOT NULL
);
ALTER TABLE "public"."poll_options" OWNER TO "postgres";
ALTER TABLE ONLY "public"."poll_options" ADD CONSTRAINT "poll_options_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."poll_options" ADD CONSTRAINT "poll_options_poll_id_fkey" FOREIGN KEY ("poll_id") REFERENCES "public"."polls"("id") ON DELETE CASCADE;
GRANT ALL ON TABLE "public"."poll_options" TO "anon";
GRANT ALL ON TABLE "public"."poll_options" TO "authenticated";
GRANT ALL ON TABLE "public"."poll_options" TO "service_role";

-- One active vote per user per poll; re-votable via upsert on (poll_id, user_id),
-- same shape as post_reactions' UNIQUE(post_id, user_id).
CREATE TABLE "public"."poll_votes" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "poll_id" uuid NOT NULL,
  "option_id" uuid NOT NULL,
  "user_id" uuid DEFAULT auth.uid() NOT NULL,
  "created_at" timestamptz DEFAULT now() NOT NULL
);
ALTER TABLE "public"."poll_votes" OWNER TO "postgres";
ALTER TABLE ONLY "public"."poll_votes" ADD CONSTRAINT "poll_votes_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."poll_votes" ADD CONSTRAINT "poll_votes_poll_id_user_id_key" UNIQUE ("poll_id", "user_id");
ALTER TABLE ONLY "public"."poll_votes" ADD CONSTRAINT "poll_votes_poll_id_fkey" FOREIGN KEY ("poll_id") REFERENCES "public"."polls"("id") ON DELETE CASCADE;
ALTER TABLE ONLY "public"."poll_votes" ADD CONSTRAINT "poll_votes_option_id_fkey" FOREIGN KEY ("option_id") REFERENCES "public"."poll_options"("id") ON DELETE CASCADE;
ALTER TABLE ONLY "public"."poll_votes" ADD CONSTRAINT "poll_votes_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE CASCADE;
GRANT ALL ON TABLE "public"."poll_votes" TO "anon";
GRANT ALL ON TABLE "public"."poll_votes" TO "authenticated";
GRANT ALL ON TABLE "public"."poll_votes" TO "service_role";
