CREATE TABLE "public"."comment_reactions" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "comment_id" uuid NOT NULL,
  "user_id" uuid DEFAULT auth.uid() NOT NULL,
  "emoji" character varying DEFAULT '❤️' NOT NULL,
  "created_at" timestamptz DEFAULT now() NOT NULL
);

ALTER TABLE "public"."comment_reactions" OWNER TO "postgres";

ALTER TABLE ONLY "public"."comment_reactions"
    ADD CONSTRAINT "comment_reactions_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."comment_reactions"
    ADD CONSTRAINT "comment_reactions_comment_id_user_id_key" UNIQUE ("comment_id", "user_id");

ALTER TABLE ONLY "public"."comment_reactions"
    ADD CONSTRAINT "comment_reactions_comment_id_fkey" FOREIGN KEY ("comment_id") REFERENCES "public"."post_comments"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."comment_reactions"
    ADD CONSTRAINT "comment_reactions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE CASCADE;

GRANT ALL ON TABLE "public"."comment_reactions" TO "anon";
GRANT ALL ON TABLE "public"."comment_reactions" TO "authenticated";
GRANT ALL ON TABLE "public"."comment_reactions" TO "service_role";

ALTER TYPE "public"."notification_type" ADD VALUE 'new_comment_reaction';
