


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE SCHEMA IF NOT EXISTS "public";


ALTER SCHEMA "public" OWNER TO "pg_database_owner";


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE TYPE "public"."role" AS ENUM (
    'admin',
    'viewer'
);


ALTER TYPE "public"."role" OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."babies" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "baby_surname" character varying NOT NULL
);


ALTER TABLE "public"."babies" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."baby_access" (
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "baby_id" "uuid" NOT NULL,
    "user_id" "uuid" DEFAULT "auth"."uid"() NOT NULL,
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "relation_to_baby" character varying DEFAULT ''::character varying NOT NULL,
    "access_level" "public"."role" DEFAULT 'viewer'::"public"."role" NOT NULL
);


ALTER TABLE "public"."baby_access" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."circles" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "baby_id" "uuid",
    "name" character varying,
    "parent_circle" "uuid"
);


ALTER TABLE "public"."circles" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."circles_access" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "circle_id" "uuid" NOT NULL,
    "user_id" "uuid" DEFAULT "auth"."uid"() NOT NULL,
    "baby_id" "uuid"
);


ALTER TABLE "public"."circles_access" OWNER TO "postgres";


ALTER TABLE "public"."circles_access" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."circles_access_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."guess_questions" (
    "baby_id" "uuid" NOT NULL,
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "type" character varying NOT NULL,
    "options" "jsonb",
    "is_active" boolean NOT NULL,
    "title" character varying,
    "description" character varying,
    "status" "text" DEFAULT 'approved'::"text" NOT NULL,
    "created_by" "uuid",
    CONSTRAINT "guess_questions_status_check" CHECK (("status" = ANY (ARRAY['pending'::"text", 'approved'::"text", 'rejected'::"text"])))
);


ALTER TABLE "public"."guess_questions" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."guesses" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "user_id" "uuid" DEFAULT "auth"."uid"() NOT NULL,
    "answer" "jsonb",
    "question_id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "baby_id" "uuid" NOT NULL
);


ALTER TABLE "public"."guesses" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."invitations" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "baby_id" "uuid" NOT NULL,
    "expires_at" timestamp with time zone NOT NULL
);


ALTER TABLE "public"."invitations" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."push_subscriptions" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "subscription" "jsonb" NOT NULL
);


ALTER TABLE "public"."push_subscriptions" OWNER TO "postgres";


ALTER TABLE "public"."push_subscriptions" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."push_subscriptions_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."users" (
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "first_name" character varying,
    "last_name" character varying,
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL
);


ALTER TABLE "public"."users" OWNER TO "postgres";


ALTER TABLE ONLY "public"."babies"
    ADD CONSTRAINT "Project_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."baby_access"
    ADD CONSTRAINT "baby_access_pkey" PRIMARY KEY ("baby_id", "user_id");



ALTER TABLE ONLY "public"."circles_access"
    ADD CONSTRAINT "circles_access_pkey" PRIMARY KEY ("circle_id", "user_id");



ALTER TABLE ONLY "public"."circles"
    ADD CONSTRAINT "circles_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."guess_questions"
    ADD CONSTRAINT "guess_questions_pkey" PRIMARY KEY ("baby_id", "id");



ALTER TABLE ONLY "public"."guesses"
    ADD CONSTRAINT "guesses_pkey" PRIMARY KEY ("user_id", "question_id");



ALTER TABLE ONLY "public"."invitations"
    ADD CONSTRAINT "invitations_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."push_subscriptions"
    ADD CONSTRAINT "push_subscriptions_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."baby_access"
    ADD CONSTRAINT "baby_access_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id");



ALTER TABLE ONLY "public"."circles_access"
    ADD CONSTRAINT "circles_access_baby_id_fkey" FOREIGN KEY ("baby_id") REFERENCES "public"."babies"("id");



ALTER TABLE ONLY "public"."circles_access"
    ADD CONSTRAINT "circles_access_circle_id_fkey" FOREIGN KEY ("circle_id") REFERENCES "public"."circles"("id");



ALTER TABLE ONLY "public"."circles_access"
    ADD CONSTRAINT "circles_access_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."circles"
    ADD CONSTRAINT "circles_baby_id_fkey" FOREIGN KEY ("baby_id") REFERENCES "public"."babies"("id");



ALTER TABLE ONLY "public"."circles"
    ADD CONSTRAINT "circles_parent_circle_fkey" FOREIGN KEY ("parent_circle") REFERENCES "public"."circles"("id");



ALTER TABLE ONLY "public"."guess_questions"
    ADD CONSTRAINT "guess_questions_baby_id_fkey" FOREIGN KEY ("baby_id") REFERENCES "public"."babies"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."guess_questions"
    ADD CONSTRAINT "guess_questions_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."guesses"
    ADD CONSTRAINT "guesses_question_id_project_id_fkey" FOREIGN KEY ("question_id", "baby_id") REFERENCES "public"."guess_questions"("id", "baby_id");



ALTER TABLE ONLY "public"."guesses"
    ADD CONSTRAINT "guesses_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."invitations"
    ADD CONSTRAINT "invitations_baby_id_fkey" FOREIGN KEY ("baby_id") REFERENCES "public"."babies"("id");



ALTER TABLE ONLY "public"."baby_access"
    ADD CONSTRAINT "project_access_project_id_fkey" FOREIGN KEY ("baby_id") REFERENCES "public"."babies"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."baby_access"
    ADD CONSTRAINT "project_access_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."push_subscriptions"
    ADD CONSTRAINT "push_subscriptions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";



GRANT ALL ON TABLE "public"."babies" TO "anon";
GRANT ALL ON TABLE "public"."babies" TO "authenticated";
GRANT ALL ON TABLE "public"."babies" TO "service_role";



GRANT ALL ON TABLE "public"."baby_access" TO "anon";
GRANT ALL ON TABLE "public"."baby_access" TO "authenticated";
GRANT ALL ON TABLE "public"."baby_access" TO "service_role";



GRANT ALL ON TABLE "public"."circles" TO "anon";
GRANT ALL ON TABLE "public"."circles" TO "authenticated";
GRANT ALL ON TABLE "public"."circles" TO "service_role";



GRANT ALL ON TABLE "public"."circles_access" TO "anon";
GRANT ALL ON TABLE "public"."circles_access" TO "authenticated";
GRANT ALL ON TABLE "public"."circles_access" TO "service_role";



GRANT ALL ON SEQUENCE "public"."circles_access_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."circles_access_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."circles_access_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."guess_questions" TO "anon";
GRANT ALL ON TABLE "public"."guess_questions" TO "authenticated";
GRANT ALL ON TABLE "public"."guess_questions" TO "service_role";



GRANT ALL ON TABLE "public"."guesses" TO "anon";
GRANT ALL ON TABLE "public"."guesses" TO "authenticated";
GRANT ALL ON TABLE "public"."guesses" TO "service_role";



GRANT ALL ON TABLE "public"."invitations" TO "anon";
GRANT ALL ON TABLE "public"."invitations" TO "authenticated";
GRANT ALL ON TABLE "public"."invitations" TO "service_role";



GRANT ALL ON TABLE "public"."push_subscriptions" TO "anon";
GRANT ALL ON TABLE "public"."push_subscriptions" TO "authenticated";
GRANT ALL ON TABLE "public"."push_subscriptions" TO "service_role";



GRANT ALL ON SEQUENCE "public"."push_subscriptions_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."push_subscriptions_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."push_subscriptions_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."users" TO "anon";
GRANT ALL ON TABLE "public"."users" TO "authenticated";
GRANT ALL ON TABLE "public"."users" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";







